package com.cary.stq.to;

public class Linkman {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.LINKMAN_ID
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private Integer linkmanId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.NAME
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.NAME_E
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String nameE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.POSITION
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String position;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.POSITION_E
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String positionE;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.TELEPHONE
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String telephone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.FAX
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String fax;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.MOBILE
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String mobile;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column linkman.EMAIL
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	private String email;

    private String refComId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.LINKMAN_ID
	 * @return  the value of linkman.LINKMAN_ID
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public Integer getLinkmanId() {
		return linkmanId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.LINKMAN_ID
	 * @param linkmanId  the value for linkman.LINKMAN_ID
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setLinkmanId(Integer linkmanId) {
		this.linkmanId = linkmanId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.NAME
	 * @return  the value of linkman.NAME
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getName() {
		return name == null? this.getNameE():name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.NAME
	 * @param name  the value for linkman.NAME
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.NAME_E
	 * @return  the value of linkman.NAME_E
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getNameE() {
		return nameE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.NAME_E
	 * @param nameE  the value for linkman.NAME_E
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setNameE(String nameE) {
		this.nameE = nameE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.POSITION
	 * @return  the value of linkman.POSITION
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.POSITION
	 * @param position  the value for linkman.POSITION
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setPosition(String position) {
		this.position = position;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.POSITION_E
	 * @return  the value of linkman.POSITION_E
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getPositionE() {
		return positionE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.POSITION_E
	 * @param positionE  the value for linkman.POSITION_E
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setPositionE(String positionE) {
		this.positionE = positionE;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.TELEPHONE
	 * @return  the value of linkman.TELEPHONE
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.TELEPHONE
	 * @param telephone  the value for linkman.TELEPHONE
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.FAX
	 * @return  the value of linkman.FAX
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.FAX
	 * @param fax  the value for linkman.FAX
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.MOBILE
	 * @return  the value of linkman.MOBILE
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.MOBILE
	 * @param mobile  the value for linkman.MOBILE
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column linkman.EMAIL
	 * @return  the value of linkman.EMAIL
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column linkman.EMAIL
	 * @param email  the value for linkman.EMAIL
	 * @abatorgenerated  Thu Jan 24 13:35:09 CST 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

    public String getRefComId() {
        return refComId;
    }

    public void setRefComId(String refComId) {
        this.refComId = refComId;
    }
}