package com.cary.stq.to;

import java.util.Date;

public class Sample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.SAMPLE_ID
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private Integer sampleId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.NAME
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.QUANTITY
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private Integer quantity;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.EXPRESS_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String expressNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.MODEL_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String modelNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.MAY_COVER_MODEL
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String mayCoverModel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.MAIN_METERIAL
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String mainMeterial;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.LOT_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String lotNo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.REVEICED_DT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private Date reveicedDt;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.BUYER
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String buyer;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.SUPPLIER
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String supplier;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.LIQUID_METHOD
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
    private String isLiquid;

	private String liquidMethod;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.PHOTO_REQURIMENT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String photoRequriment;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.SPECIFIC_REQURIMENT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String specificRequriment;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.CONCENTRATION_GT1
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String concentrationGt1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.DANGEROUS_CODE
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String dangerousCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column sample.DANGEROUS_REMARKS
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	private String dangerousRemarks;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.SAMPLE_ID
	 * @return  the value of sample.SAMPLE_ID
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public Integer getSampleId() {
		return sampleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.SAMPLE_ID
	 * @param sampleId  the value for sample.SAMPLE_ID
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setSampleId(Integer sampleId) {
		this.sampleId = sampleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.NAME
	 * @return  the value of sample.NAME
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.NAME
	 * @param name  the value for sample.NAME
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.QUANTITY
	 * @return  the value of sample.QUANTITY
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.QUANTITY
	 * @param quantity  the value for sample.QUANTITY
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.EXPRESS_NO
	 * @return  the value of sample.EXPRESS_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getExpressNo() {
		return expressNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.EXPRESS_NO
	 * @param expressNo  the value for sample.EXPRESS_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setExpressNo(String expressNo) {
		this.expressNo = expressNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.MODEL_NO
	 * @return  the value of sample.MODEL_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getModelNo() {
		return modelNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.MODEL_NO
	 * @param modelNo  the value for sample.MODEL_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setModelNo(String modelNo) {
		this.modelNo = modelNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.MAY_COVER_MODEL
	 * @return  the value of sample.MAY_COVER_MODEL
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getMayCoverModel() {
		return mayCoverModel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.MAY_COVER_MODEL
	 * @param mayCoverModel  the value for sample.MAY_COVER_MODEL
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setMayCoverModel(String mayCoverModel) {
		this.mayCoverModel = mayCoverModel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.MAIN_METERIAL
	 * @return  the value of sample.MAIN_METERIAL
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getMainMeterial() {
		return mainMeterial;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.MAIN_METERIAL
	 * @param mainMeterial  the value for sample.MAIN_METERIAL
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setMainMeterial(String mainMeterial) {
		this.mainMeterial = mainMeterial;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.LOT_NO
	 * @return  the value of sample.LOT_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getLotNo() {
		return lotNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.LOT_NO
	 * @param lotNo  the value for sample.LOT_NO
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setLotNo(String lotNo) {
		this.lotNo = lotNo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.REVEICED_DT
	 * @return  the value of sample.REVEICED_DT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public Date getReveicedDt() {
		return reveicedDt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.REVEICED_DT
	 * @param reveicedDt  the value for sample.REVEICED_DT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setReveicedDt(Date reveicedDt) {
		this.reveicedDt = reveicedDt;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.BUYER
	 * @return  the value of sample.BUYER
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getBuyer() {
		return buyer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.BUYER
	 * @param buyer  the value for sample.BUYER
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setBuyer(String buyer) {
		this.buyer = buyer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.SUPPLIER
	 * @return  the value of sample.SUPPLIER
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getSupplier() {
		return supplier;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.SUPPLIER
	 * @param supplier  the value for sample.SUPPLIER
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.LIQUID_METHOD
	 * @return  the value of sample.LIQUID_METHOD
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getLiquidMethod() {
		return liquidMethod;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.LIQUID_METHOD
	 * @param liquidMethod  the value for sample.LIQUID_METHOD
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setLiquidMethod(String liquidMethod) {
		this.liquidMethod = liquidMethod;
	}

    public String getLiquid() {
        return isLiquid;
    }

    public void setLiquid(String liquid) {
        isLiquid = liquid;
    }

    /**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.PHOTO_REQURIMENT
	 * @return  the value of sample.PHOTO_REQURIMENT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getPhotoRequriment() {
		return photoRequriment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.PHOTO_REQURIMENT
	 * @param photoRequriment  the value for sample.PHOTO_REQURIMENT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setPhotoRequriment(String photoRequriment) {
		this.photoRequriment = photoRequriment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.SPECIFIC_REQURIMENT
	 * @return  the value of sample.SPECIFIC_REQURIMENT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getSpecificRequriment() {
		return specificRequriment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.SPECIFIC_REQURIMENT
	 * @param specificRequriment  the value for sample.SPECIFIC_REQURIMENT
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setSpecificRequriment(String specificRequriment) {
		this.specificRequriment = specificRequriment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.CONCENTRATION_GT1
	 * @return  the value of sample.CONCENTRATION_GT1
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getConcentrationGt1() {
		return concentrationGt1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.CONCENTRATION_GT1
	 * @param concentrationGt1  the value for sample.CONCENTRATION_GT1
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setConcentrationGt1(String concentrationGt1) {
		this.concentrationGt1 = concentrationGt1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.DANGEROUS_CODE
	 * @return  the value of sample.DANGEROUS_CODE
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getDangerousCode() {
		return dangerousCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.DANGEROUS_CODE
	 * @param dangerousCode  the value for sample.DANGEROUS_CODE
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setDangerousCode(String dangerousCode) {
		this.dangerousCode = dangerousCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column sample.DANGEROUS_REMARKS
	 * @return  the value of sample.DANGEROUS_REMARKS
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public String getDangerousRemarks() {
		return dangerousRemarks;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column sample.DANGEROUS_REMARKS
	 * @param dangerousRemarks  the value for sample.DANGEROUS_REMARKS
	 * @abatorgenerated  Thu Jan 24 17:53:11 CST 2013
	 */
	public void setDangerousRemarks(String dangerousRemarks) {
		this.dangerousRemarks = dangerousRemarks;
	}
}