package com.cary.stq.to;

import java.util.ArrayList;
import java.util.List;

public class Testitems {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.TID
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private Integer tid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.ITEM_ID
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String itemId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.ITEM_DESC
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String itemDesc;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.SUB_ITEM_ID1
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String subItemId1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.SUB_ITEM_DESC1
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String subItemDesc1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.SUB_ITEM_ID2
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String subItemId2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.SUB_ITEM_DESC2
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String subItemDesc2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.SUB_ITEM_ID3
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String subItemId3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.SUB_ITEM_DESC3
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	private String subItemDesc3;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column testitems.STANDARD
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
    private List<Testitems> children;

    private String id;

    private String text;

	private String standard;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.TID
	 * @return  the value of testitems.TID
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.TID
	 * @param tid  the value for testitems.TID
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.ITEM_ID
	 * @return  the value of testitems.ITEM_ID
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getItemId() {
		return itemId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.ITEM_ID
	 * @param itemId  the value for testitems.ITEM_ID
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.ITEM_DESC
	 * @return  the value of testitems.ITEM_DESC
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getItemDesc() {
		return itemDesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.ITEM_DESC
	 * @param itemDesc  the value for testitems.ITEM_DESC
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.SUB_ITEM_ID1
	 * @return  the value of testitems.SUB_ITEM_ID1
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getSubItemId1() {
		return subItemId1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.SUB_ITEM_ID1
	 * @param subItemId1  the value for testitems.SUB_ITEM_ID1
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setSubItemId1(String subItemId1) {
		this.subItemId1 = subItemId1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.SUB_ITEM_DESC1
	 * @return  the value of testitems.SUB_ITEM_DESC1
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getSubItemDesc1() {
		return subItemDesc1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.SUB_ITEM_DESC1
	 * @param subItemDesc1  the value for testitems.SUB_ITEM_DESC1
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setSubItemDesc1(String subItemDesc1) {
		this.subItemDesc1 = subItemDesc1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.SUB_ITEM_ID2
	 * @return  the value of testitems.SUB_ITEM_ID2
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getSubItemId2() {
		return subItemId2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.SUB_ITEM_ID2
	 * @param subItemId2  the value for testitems.SUB_ITEM_ID2
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setSubItemId2(String subItemId2) {
		this.subItemId2 = subItemId2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.SUB_ITEM_DESC2
	 * @return  the value of testitems.SUB_ITEM_DESC2
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getSubItemDesc2() {
		return subItemDesc2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.SUB_ITEM_DESC2
	 * @param subItemDesc2  the value for testitems.SUB_ITEM_DESC2
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setSubItemDesc2(String subItemDesc2) {
		this.subItemDesc2 = subItemDesc2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.SUB_ITEM_ID3
	 * @return  the value of testitems.SUB_ITEM_ID3
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getSubItemId3() {
		return subItemId3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.SUB_ITEM_ID3
	 * @param subItemId3  the value for testitems.SUB_ITEM_ID3
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setSubItemId3(String subItemId3) {
		this.subItemId3 = subItemId3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.SUB_ITEM_DESC3
	 * @return  the value of testitems.SUB_ITEM_DESC3
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getSubItemDesc3() {
		return subItemDesc3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.SUB_ITEM_DESC3
	 * @param subItemDesc3  the value for testitems.SUB_ITEM_DESC3
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setSubItemDesc3(String subItemDesc3) {
		this.subItemDesc3 = subItemDesc3;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column testitems.STANDARD
	 * @return  the value of testitems.STANDARD
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public String getStandard() {
		return standard;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column testitems.STANDARD
	 * @param standard  the value for testitems.STANDARD
	 * @abatorgenerated  Wed Jan 30 14:18:48 CST 2013
	 */
	public void setStandard(String standard) {
		this.standard = standard;
	}

    public List<Testitems> getChildren() {
        return children == null? new ArrayList<Testitems>():children;
    }

    public void setChildren(List<Testitems> children) {
        this.children = children;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }
}